_target_: pytorch_lightning.Trainer

accelerator: cpu
precision: 16 # Original 32

min_epochs: 1
max_epochs: 3

val_check_interval: 0.5

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 1
