_target_: src.models.hf_model.SequenceClassificationTransformer

num_labels: 3 # TODO: SET TO 3 In higher level Override me in your experiment config!
huggingface_model: "pysentimiento/robertuito-base-uncased"
learning_rate: 3e-5
batch_size: ${datamodule.batch_size}